### ISSUE TITLE
Clean up HTTPS answer parsing

### ISSUE THREAD

**Issue by chris-wood** [cloudflare/odoh-client-rs#8]
It's currently [somewhat hacky](https://github.com/cloudflare/odoh-client-rs/pull/7#discussion_r545941738). Once upstream support for HTTPS resource record parsing lands, we can clean this up and properly parse out the `odohconfig` SvcbParam value from DNS.

**Comment by tanyav2** [comment]
Given that IETF is leaning towards preferring well known endpoint for querying the config, I think we can close this issue.
